python train/run_cmaes_all.py \
  --abs_step 5 \
  --tot_step 50 \
  --iter 15 \
  --trial 1 \
  --pop_size 40 \
  --sigma 2.5 \
  --env forming \
  --Kb 200 \
  --mu 5.0 \
  --max_dist 0.001 \
  --target_dir ../data/forming_pos_save/cloth_pos.npy