python training/run_cmaes_all.py \
  --abs_step 10 \
  --tot_step 50 \
  --iter 30 \
  --trial 1 \
  --pop_size 40 \
  --sigma 2.5 \
  --env pick \
  --Kb 200 \
  --mu 5.0 \
  --max_dist 0.001 \
  --reward_name compute_reward_pick_fold