python run_cmaes_all.py \
  --abs_step 10 \
  --tot_step 80 \
  --iter 15 \
  --trial curve_7 \
  --pop_size 40 \
  --sigma 2.5 \
  --env folding \
  --Kb 400 \
  --mu 5.0 \
  --max_dist 0.001 \
  --reward_name compute_reward_7