python training/run_cmaes_parameter.py \
  --tot_step 50 \
  --iter 5 \
  --trial 0 \
  --pop_size 10 \
  --sigma 0.1 \
  --env card \
  --Kb 1000 \
  --mu 1.0 \
  --mu_cloth 0.001 \
  --traj init_traj_card
