python training/run_cmaes_all.py \
  --abs_step 5 \
  --tot_step 50 \
  --iter 10 \
  --trial 1 \
  --pop_size 40 \
  --sigma 2.5 \
  --env balancing \
  --Kb 100 \
  --mu 5.0 \
  --load_dir ../data/throwing_state \
  --max_dist 0.001 \
  --reward_name compute_reward_throwing